name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      USERNAME_DOCKER: ${{ secrets.DOCKERHUB_USERNAME }}
    steps:
      - uses: actions/checkout@v3
  
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build the Docker image
        run: docker build ./Parking.Management.Dashboard/Backend --file Dockerfile --tag  $USERNAME_DOCKER/backend-pm:${{ env.GITHUB_SHA }}

      - name: Push Docker image
        run: docker push  $USERNAME_DOCKER/backend-pm:${{ env.GITHUB_SHA }}
